from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from phenotypic._core._image import Image

import numpy as np
import cv2
from sklearn.mixture import GaussianMixture

from ..abc_ import ObjectRefiner


class ExtractColonyCore(ObjectRefiner):
    """Extract the bright inoculum core from each colony using Gaussian mixture modeling.

    Fits a two-component Gaussian mixture model to each labeled colony's intensity
    histogram, separating the bright inoculum core from the dimmer surrounding halo.
    Regions with insufficient intensity contrast are left unchanged; morphological
    opening and closing refine the extracted core shape. Returns an image whose
    ``objmap`` contains core-only masks rather than full colony footprints.

    For an overview of refinement strategies, see
    :doc:`/explanation/refinement_strategies`.

    Best For:
        - Rich-media plates (YPD, LB) where pinned inocula develop dense bright
          centers surrounded by a dimmer outgrowth halo.
        - High-density 96-well or 384-well arrays where core isolation reduces
          measurement spillover between adjacent wells.
        - Time-course experiments where inoculum mass is the feature of interest,
          so size and intensity reflect the growth core rather than diffusion halos.

    Consider Also:
        - :class:`MaskErosion` for uniform inward shrinking when inoculum cores
          are not intensity-distinct from the surrounding halo.
        - :class:`InoculumDetector` when core detection is needed as a standalone
          detection step rather than a post-detection refinement.
        - :class:`RemoveLowCircularity` for shape-based filtering when halos distort
          circularity measurements without requiring intensity separation.

    Args:
        n_components: Number of Gaussian mixture components fitted per colony.
            Use 2 for the canonical bright-core versus dim-halo split; higher
            values add intermediate intensity modes but increase fitting cost and
            risk over-segmentation. Default: 2.
        separation_threshold: Normalized mean separation (|mu_1 - mu_0| /
            (sigma_0 + sigma_1)) below which a colony is left unchanged. Typical
            range: 0.5--1.2. Higher values require a more bimodal histogram before
            any core is extracted; lower values extract cores from subtler intensity
            gradients. Default: 0.8.
        min_core_area: Minimum extracted core area in pixels. Colonies smaller than
            this are kept as-is without attempting GMM fitting; extracted cores
            smaller than this fall back to the original mask. Scale proportionally
            with image resolution. Typical range: 10--500. Default: 30.
        morph_open_radius: Radius of the elliptical structuring element for
            morphological opening applied after GMM classification. Removes thin
            protrusions and isolated noise specks from the core mask. Set to 0 to
            disable. Typical range: 0--5. Default: 1.
        morph_close_radius: Radius of the elliptical structuring element for
            morphological closing applied after opening. Fills small gaps and
            holes within the core mask. Set to 0 to disable. Typical range: 0--5.
            Default: 2.

    Returns:
        Image: Input image with ``objmap`` updated so each labeled region
        contains only the bright core pixels; ``objmask`` is unchanged.

    Raises:
        pydantic.ValidationError: If a parameter is given a value of the wrong
            type (e.g. a non-numeric ``separation_threshold``).

    See Also:
        :doc:`/how_to/notebooks/refine_noisy_boundaries` for core extraction
        workflows on real plate images.
    """

    n_components: int = 2
    separation_threshold: float = 0.8
    min_core_area: int = 30
    morph_open_radius: int = 1
    morph_close_radius: int = 2

    # ------------------------------------------------------------------
    # Static helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _build_ellipse_kernel(radius: int) -> np.ndarray | None:
        """Create an elliptical morphological structuring element for opening/closing.

        Args:
            radius (int): Radius of the kernel in pixels. When *radius* <= 0,
                returns ``None`` (indicating no morphological operation).

        Returns:
            np.ndarray | None: A ``(2*radius+1, 2*radius+1)`` uint8 structuring
                element with elliptical (disk-like) shape generated by
                ``cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (k, k))`` where
                k = 2*radius+1. Returns ``None`` when *radius* is non-positive,
                allowing calling code to skip morphological operations when disabled.

        Notes:
            Elliptical kernels are isotropic (uniform in all directions), making them
            ideal for preserving rounded colony shapes during morphological operations.
            They are generated by OpenCV and produce symmetric disk-like binary patterns.
        """
        if radius <= 0:
            return None
        k = 2 * radius + 1
        return cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (k, k))

    @staticmethod
    def _normalized_separation(gmm: GaussianMixture) -> float:
        """Compute normalized mean separation of a fitted Gaussian mixture model.

        Computes the intensity contrast between two Gaussian components normalized by
        their combined standard deviation. This metric quantifies whether the two
        components (typically bright core vs. dim halo) are well-separated relative to
        their spread.

        Args:
            gmm (GaussianMixture): A fitted Gaussian mixture model from scikit-learn
                (typically with n_components=2). Must have at least 2 components.
                The model should be fitted on 1-D intensity data (reshaped as column
                vector for binary classification).

        Returns:
            float: Normalized separation defined as
                |mu_1 - mu_0| / (sigma_0 + sigma_1), where mu_i is the mean and
                sigma_i is the standard deviation of component i. Returns 0.0 when
                the summed standard deviations are negligible (< 1e-10), indicating
                very tight, nearly overlapping components. Higher values (>0.5)
                indicate well-separated components; lower values (<0.3) suggest
                poor separation and unreliable core extraction.

        Raises:
            ValueError: If *gmm* has fewer than 2 components; this function
                requires bimodal or higher-order separation.

        Notes:
            - The metric is invariant to resolution (depends on intensity values
              and camera properties, not pixel counts).
            - For colony imaging, typical separation values range from 0.3 (barely
              separated, diffuse halo) to 1.5+ (sharp bright core, dark surround).
            - The function extracts variance from gmm.covariances_, handling both
              full (ndim=3), diagonal (ndim=2), and spherical (ndim=1) covariance
              types by taking appropriate slices.
        """
        mu = gmm.means_.ravel()
        cov = gmm.covariances_
        if cov.ndim == 3:
            var = cov[:, 0, 0]
        elif cov.ndim == 2:
            var = cov[:, 0]
        else:
            var = cov.ravel()
        sigma_sum = np.sqrt(var[0]) + np.sqrt(var[1])
        if sigma_sum < 1e-10:
            return 0.0
        return float(np.abs(mu[1] - mu[0]) / sigma_sum)

    @staticmethod
    def _extract_single_core(
            intensity: np.ndarray,
            label_map: np.ndarray,
            label: int,
            n_components: int,
            separation_threshold: float,
            min_core_area: int,
            open_kernel: np.ndarray | None,
            close_kernel: np.ndarray | None,
    ) -> np.ndarray:
        """Extract the bright core from a single labelled region using GMM.

        Core extraction pipeline for one colony region:
        1. Extract pixels from the labelled region
        2. Fit a Gaussian mixture model (GMM) to the region's intensity histogram
        3. Compute normalized separation between components
        4. If separation is insufficient, return original mask unchanged
        5. Identify bright component (higher mean) and predict labels for pixels
        6. Apply morphological opening/closing to refine core shape
        7. Select largest connected component above min_core_area
        8. Return binary core mask for this region

        Args:
            intensity (np.ndarray): 2-D float grayscale intensity image
                (e.g., image.detect_mat or normalized RGB). Shape (H, W).
            label_map (np.ndarray): Integer label map with same shape as *intensity*.
                Pixel value 0 = background; >0 = object label.
            label (int): The specific label value to process within label_map.
            n_components (int): Number of Gaussian components to fit per region.
                Typically 2 (bright core vs. dim halo).
            separation_threshold (float): Normalized separation below which the
                original region mask is returned unchanged (no extraction attempted).
                Typical range 0.5–1.2.
            min_core_area (int): Minimum core area in pixels. Extracted cores
                or final connected components smaller than this are discarded;
                the original region mask is returned instead.
            open_kernel (np.ndarray | None): Structuring element for morphological
                opening (shrink by eroding then dilating). When ``None``, skip opening.
            close_kernel (np.ndarray | None): Structuring element for morphological
                closing (expand by dilating then eroding). When ``None``, skip closing.

        Returns:
            np.ndarray: Boolean mask (same shape as *intensity*) indicating the
                extracted core region. True pixels belong to the core; False pixels
                are background or excluded. If extraction fails, returns the original
                region mask to avoid data loss.

        Notes:
            - The extraction is localized to the bounding box of the region
              (computational efficiency; reduces memory usage for sparse objects).
            - Regions smaller than min_core_area are returned as-is without
              attempting GMM fitting (no point fitting on tiny regions).
            - Uniform regions (std < 1e-6) are returned unchanged; GMM fitting would fail.
            - The GMM is fitted with covariance_type='full' and random_state=42
              for reproducibility.
            - After morphological operations, if no valid connected component survives
              min_core_area, the original region mask is returned (graceful fallback).
            - Morphological operations may slightly shift core boundaries (~1–3 pixels)
              and can cause 5–10% edge erosion/dilation; quantified impact depends on
              kernel size.
        """
        mask = label_map == label
        area = int(mask.sum())

        # Too small — keep as-is
        if area < min_core_area:
            return mask

        pixels = intensity[mask].reshape(-1, 1).astype(np.float64)

        # Uniform region — keep as-is
        if pixels.std() < 1e-6:
            return mask

        gmm = GaussianMixture(
                n_components=n_components,
                covariance_type="full",
                n_init=3,
                random_state=42,
        )
        gmm.fit(pixels)
        sep = ExtractColonyCore._normalized_separation(gmm)

        if sep < separation_threshold:
            return mask

        # Determine bounding box of the region
        rows, cols = np.where(mask)
        r_min, r_max = rows.min(), rows.max() + 1
        c_min, c_max = cols.min(), cols.max() + 1

        roi = intensity[r_min:r_max, c_min:c_max]
        mask_roi = mask[r_min:r_max, c_min:c_max]

        bright_comp = int(np.argmax(gmm.means_.ravel()))
        labels_flat = gmm.predict(roi.reshape(-1, 1).astype(np.float64))
        core_roi = (labels_flat.reshape(roi.shape) == bright_comp) & mask_roi

        core_u8 = core_roi.astype(np.uint8) * 255
        if open_kernel is not None:
            core_u8 = cv2.morphologyEx(core_u8, cv2.MORPH_OPEN, open_kernel)
        if close_kernel is not None:
            core_u8 = cv2.morphologyEx(core_u8, cv2.MORPH_CLOSE, close_kernel)

        n_labels, cc_map, stats, _ = cv2.connectedComponentsWithStats(
                core_u8, connectivity=8
        )

        best_cc = -1
        best_area = 0
        for lbl in range(1, n_labels):
            a = stats[lbl, cv2.CC_STAT_AREA]
            if a >= min_core_area and a > best_area:
                best_cc = lbl
                best_area = a

        if best_cc < 0:
            # No valid connected component — keep original mask
            return mask

        H, W = intensity.shape
        core_mask = np.zeros((H, W), dtype=bool)
        core_mask[r_min:r_max, c_min:c_max] = cc_map == best_cc
        return core_mask

    @staticmethod
    def _extract_cores(
            intensity_array: np.ndarray,
            label_map: np.ndarray,
            n_components: int = 2,
            separation_threshold: float = 0.8,
            min_core_area: int = 30,
            morph_open_radius: int = 1,
            morph_close_radius: int = 2,
    ) -> np.ndarray:
        """Extract bright cores from all labelled regions in a label map using GMM.

        Batch processing function that iterates over all unique labels in a labelled map,
        fits a Gaussian mixture model (GMM) to each region's intensity distribution,
        and extracts the bright core component. This is the main computational entry
        point; it orchestrates kernel building, per-region extraction, and result
        composition into a refined label map.

        Args:
            intensity_array (np.ndarray): 2-D float grayscale intensity image
                (H, W). Typically image.detect_mat (standardized to [0, 1] or [0, 255]).
            label_map (np.ndarray): Integer-labelled object map with same shape as
                *intensity_array*. Pixel value 0 = background; 1, 2, 3, ... = object
                labels. Usually from image.objmap[:].
            n_components (int): Number of Gaussian components to fit per region
                (default 2). Standard choice separates bright core from dim halo;
                higher values (3+) capture additional intensity modes but increase
                fitting cost and risk over-segmentation.
            separation_threshold (float): Normalized mean separation threshold below
                which a region is left unchanged (default 0.8, range 0.0–1.0+).
                Prevents extraction when intensity contrast is insufficient; e.g.,
                separation=0.7 indicates weak separation, suggesting the halo is
                nearly as bright as the core.
            min_core_area (int): Minimum core area in pixels (default 30).
                Regions with area < min_core_area are kept as-is without attempting
                extraction. Extracted cores or final connected components smaller than
                this are discarded; the original region mask is returned instead.
            morph_open_radius (int): Radius of elliptical kernel for morphological
                opening (default 1, range 0–5). Opening removes thin protrusions and
                noise speckles. Set to 0 to disable. Typical values:
                - 0: No opening; retain GMM shape exactly.
                - 1: Remove ~1–3 pixel speckles (salt-and-pepper noise).
                - 2–3: Remove ~3–7 pixel protrusions; more aggressive smoothing.
                - >4: Excessive; risk merging or removing legitimate core structures.
            morph_close_radius (int): Radius of elliptical kernel for morphological
                closing (default 2, range 0–5). Closing fills gaps and holes within
                cores. Set to 0 to disable. Typical values:
                - 0: No closing; keep open result exactly.
                - 1: Fill gaps ~1–3 pixels wide.
                - 2 (default): Fill moderate gaps; balance closure and integrity.
                - 3–4: Aggressively fill ~5–8 pixel voids; risk artificial inflation.
                - >5: Excessive; risk bridging separate cores.

        Returns:
            np.ndarray: Refined integer label map with the same shape and dtype as
                *label_map*. Each pixel retains its original label if the region
                was not refined (e.g., separation too low, region too small) or its
                label if the region was successfully extracted (0 if the pixel is
                outside the extracted core). Non-extracted pixels are 0 (background).

        Notes:
            - All unique labels (except 0) in label_map are processed independently.
            - Processing order is arbitrary; results are deterministic within each region.
            - Computational cost scales linearly with the number of labelled objects.
              On typical 96-well plates (~80–96 objects), processing is <100 ms.
              On 384-well plates (>300 objects) or megapixel images, memory/time may
              be a constraint.
            - Each region's GMM is fitted with covariance_type='full' and
              random_state=42 for reproducibility.
            - Regions are processed with a bounding-box optimization for memory
              efficiency; only pixels within each region's bounding box are analyzed.
            - Graceful fallback: If GMM extraction fails or no valid core survives
              post-processing, the original region mask is returned (no data loss).
        """
        open_kernel = ExtractColonyCore._build_ellipse_kernel(morph_open_radius)
        close_kernel = ExtractColonyCore._build_ellipse_kernel(morph_close_radius)

        labels = np.unique(label_map)
        labels = labels[labels != 0]

        output = np.zeros_like(label_map)

        for label in labels:
            core_mask = ExtractColonyCore._extract_single_core(
                    intensity_array,
                    label_map,
                    label,
                    n_components,
                    separation_threshold,
                    min_core_area,
                    open_kernel,
                    close_kernel,
            )
            output[core_mask] = label

        return output

    def _operate(self, image: Image) -> Image:
        intensity = image.detect_mat[:].astype(np.float64)
        label_map = image.objmap[:]

        refined = self._extract_cores(
                intensity_array=intensity,
                label_map=label_map,
                n_components=self.n_components,
                separation_threshold=self.separation_threshold,
                min_core_area=self.min_core_area,
                morph_open_radius=self.morph_open_radius,
                morph_close_radius=self.morph_close_radius,
        )

        image.objmap[:] = refined
        return image
