"""Developer tools shared across fungal colony plate workflows.

Lightweight helpers for timing, mask validation, constants, color conversions, error
handling, and HDF storage used by the processing pipeline. Includes a timed execution
decorator, mask validators, colourspace utilities, custom exceptions, and HDF helpers
for persisting plate datasets and measurements.

Advanced users can access GridInferenceMixin and FootprintMixin for creating custom
grid-based operations and morphological footprints.

The ``register`` submodule provides registry utilities for extensible components
like plotters and analysis plugins.

The ``_io_constants`` submodule is the single source of truth for CLI ↔ GUI
artifact filenames, directory names, JSON contract keys, and path helpers
(re-exported here at package level for convenience).
"""

from . import colourspace, constants_, exceptions_, napari_, register, slurm, slurm_
from . import _io_constants
from ._column_ref import ColumnRef, ColumnRefList, ColumnSource
from ._io_constants import (
    # Filenames (CLI artifacts)
    ANALYSIS_CSV,
    ANALYSIS_FULL_PARQUET,
    ANALYSIS_HTML,
    ANALYSIS_PARQUET,
    ANALYSIS_SCATTER_JSON,
    CHUNK_LOCK,
    CHUNK_MANIFEST_JSON,
    CHUNK_STATE_JSON,
    DASHBOARD_HTML,
    DATASET_AGGREGATED_PARQUET,
    DIR_CHUNKS,
    DIR_DELIVERABLES,
    DIR_HDF,
    DIR_INSPECT,
    DIR_LOGS,
    DIR_MEASUREMENTS,
    DIR_MEASUREMENTS_BY_FEATURE,
    DIR_OVERLAYS,
    DIR_PHENOTYPIC,
    DIR_PROGRESS,
    DIR_QC,
    DIR_RECOMPILE,
    DIR_RECOMPILE_SHARDS,
    DIR_RECOMPILE_STATUS,
    DIR_RESULTS,
    DIR_SLURM_SCRIPTS,
    FAILURES_JSONL,
    JOB_METADATA_JSON,
    MANIFEST_JSON,
    MASTER_MEASUREMENTS_CSV,
    MASTER_MEASUREMENTS_PARQUET,
    MEASUREMENTS_CSV,
    MEASUREMENTS_PARQUET,
    OVERLAY_MANIFEST_JSON,
    PIPELINE_JSON,
    PROCESSING_EVENTS_LOG,
    PROCESSING_REPORT_HTML,
    PROCESSING_STATE_JSON,
    QC_CONFIG_JSON,
    QC_MEMBERS_PARQUET,
    QC_REVIEW_STATE_JSON,
    QC_SUMMARY_PARQUET,
    README_MD,
    RECOMPILE_TASK_MANIFEST_JSON,
    SENTINEL_RESUBMITTED_MARKER,
    STDOUT_LOG,
    # Namespace classes
    ChunkManifestKey,
    ChunkStateKey,
    DashboardManifestKey,
    DashboardManifestSlurmInfoKey,
    EnvVar,
    HdfAttr,
    JobMetadataKey,
    ModulePath,
    ProcessingStateKey,
    # Path helpers
    analysis_csv_path,
    analysis_full_parquet_path,
    analysis_html_path,
    analysis_parquet_path,
    analysis_scatter_json_path,
    chunk_lock_path,
    chunk_manifest_path,
    chunk_parquet_filename,
    chunk_parquet_path,
    chunk_state_path,
    chunks_dir,
    checkpoint_lock_filename,
    checkpoint_lock_path,
    dashboard_html_path,
    dataset_hdf_dir,
    dataset_measurements_dir,
    dataset_overlays_dir,
    dataset_results_dir,
    default_output_dir_name,
    deliverables_dir,
    event_log_path,
    failures_jsonl_path,
    job_metadata_path,
    load_image_from_hdf,
    load_master_measurements,
    logs_dir,
    manifest_json_path,
    master_measurements_csv_path,
    master_measurements_parquet_path,
    measurements_by_feature_dir,
    measurements_csv_path,
    measurements_parquet_path,
    overlay_manifest_path,
    phenotypic_cache_dir,
    phenotypic_cache_pipeline_json_path,
    pipeline_json_path,
    processing_report_html_path,
    processing_state_path,
    progress_dir,
    qc_config_json_path,
    qc_dir,
    qc_members_parquet_path,
    qc_review_state_path,
    qc_summary_parquet_path,
    readme_md_path,
    read_run_manifest,
    recompile_dir,
    recompile_status_dir,
    resolve_event_log_path,
    resolve_execution_mode,
    resolve_manifest_json_path,
    resolve_processing_state_path,
    resolve_progress_dir,
    migrate_legacy_machine_state,
    clear_machine_state,
    results_dir,
    sentinel_resubmitted_path,
    shard_parquet_filename,
    slurm_scripts_dir,
    task_status_filename,
    task_status_path,
)
from .funcs_ import is_binary_mask, timed_execution
from .hdf_ import HDF
from .mixin import ClipControlMixin, FootprintMixin, GridInferenceMixin, LazyWidgetMixin
from .typing_ import ProcessOnlyLayer

__all__ = [
    # Mixins / utilities (existing)
    "ClipControlMixin",
    "ColumnRef",
    "ColumnRefList",
    "ColumnSource",
    "FootprintMixin",
    "GridInferenceMixin",
    "HDF",
    "LazyWidgetMixin",
    "colourspace",
    "constants_",
    "exceptions_",
    "is_binary_mask",
    "napari_",
    "register",
    "slurm",
    "slurm_",
    "timed_execution",
    # Typing aliases (closed value sets)
    "ProcessOnlyLayer",
    # I/O constants module (also re-exported below)
    "_io_constants",
    # Filename constants
    "ANALYSIS_CSV",
    "ANALYSIS_FULL_PARQUET",
    "ANALYSIS_HTML",
    "ANALYSIS_PARQUET",
    "ANALYSIS_SCATTER_JSON",
    "CHUNK_LOCK",
    "CHUNK_MANIFEST_JSON",
    "CHUNK_STATE_JSON",
    "DASHBOARD_HTML",
    "DATASET_AGGREGATED_PARQUET",
    "FAILURES_JSONL",
    "JOB_METADATA_JSON",
    "MANIFEST_JSON",
    "MASTER_MEASUREMENTS_CSV",
    "MASTER_MEASUREMENTS_PARQUET",
    "MEASUREMENTS_CSV",
    "MEASUREMENTS_PARQUET",
    "OVERLAY_MANIFEST_JSON",
    "PIPELINE_JSON",
    "PROCESSING_EVENTS_LOG",
    "PROCESSING_REPORT_HTML",
    "PROCESSING_STATE_JSON",
    "QC_CONFIG_JSON",
    "QC_MEMBERS_PARQUET",
    "QC_REVIEW_STATE_JSON",
    "QC_SUMMARY_PARQUET",
    "README_MD",
    "RECOMPILE_TASK_MANIFEST_JSON",
    "SENTINEL_RESUBMITTED_MARKER",
    "STDOUT_LOG",
    # Directory constants
    "DIR_CHUNKS",
    "DIR_DELIVERABLES",
    "DIR_HDF",
    "DIR_INSPECT",
    "DIR_LOGS",
    "DIR_MEASUREMENTS",
    "DIR_MEASUREMENTS_BY_FEATURE",
    "DIR_OVERLAYS",
    "DIR_PHENOTYPIC",
    "DIR_PROGRESS",
    "DIR_QC",
    "DIR_RECOMPILE",
    "DIR_RECOMPILE_SHARDS",
    "DIR_RECOMPILE_STATUS",
    "DIR_RESULTS",
    "DIR_SLURM_SCRIPTS",
    # Namespace classes for JSON keys + dispatch
    "ChunkManifestKey",
    "ChunkStateKey",
    "DashboardManifestKey",
    "DashboardManifestSlurmInfoKey",
    "EnvVar",
    "HdfAttr",
    "JobMetadataKey",
    "ModulePath",
    "ProcessingStateKey",
    # Path helpers
    "analysis_csv_path",
    "analysis_full_parquet_path",
    "analysis_html_path",
    "analysis_parquet_path",
    "analysis_scatter_json_path",
    "chunk_lock_path",
    "chunk_manifest_path",
    "chunk_parquet_filename",
    "chunk_parquet_path",
    "chunk_state_path",
    "chunks_dir",
    "checkpoint_lock_filename",
    "checkpoint_lock_path",
    "dashboard_html_path",
    "dataset_hdf_dir",
    "dataset_measurements_dir",
    "dataset_overlays_dir",
    "dataset_results_dir",
    "default_output_dir_name",
    "deliverables_dir",
    "event_log_path",
    "failures_jsonl_path",
    "job_metadata_path",
    "load_image_from_hdf",
    "load_master_measurements",
    "logs_dir",
    "manifest_json_path",
    "master_measurements_csv_path",
    "master_measurements_parquet_path",
    "measurements_by_feature_dir",
    "measurements_csv_path",
    "measurements_parquet_path",
    "migrate_legacy_machine_state",
    "clear_machine_state",
    "overlay_manifest_path",
    "phenotypic_cache_dir",
    "phenotypic_cache_pipeline_json_path",
    "pipeline_json_path",
    "processing_report_html_path",
    "processing_state_path",
    "progress_dir",
    "qc_config_json_path",
    "qc_dir",
    "qc_members_parquet_path",
    "qc_review_state_path",
    "qc_summary_parquet_path",
    "readme_md_path",
    "read_run_manifest",
    "recompile_dir",
    "recompile_status_dir",
    "resolve_event_log_path",
    "resolve_execution_mode",
    "resolve_manifest_json_path",
    "resolve_processing_state_path",
    "resolve_progress_dir",
    "results_dir",
    "sentinel_resubmitted_path",
    "shard_parquet_filename",
    "slurm_scripts_dir",
    "task_status_filename",
    "task_status_path",
]
