"""SLURM bash script generation for the PhenoTypic CLI.

This module generates standalone bash scripts for autonomous SLURM execution.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Dict, List, Any
import shlex

from ._cli_types import Dataset, ExecutionConfig
from ._cli_utils import SLURM_THREAD_PIN_BASH, get_python_command
from phenotypic.sdk_ import event_log_path, logs_dir, slurm_scripts_dir
from phenotypic.sdk_.slurm._sbatch import (
    format_sbatch_directives as _format_sbatch_directives,
)
from phenotypic.sdk_.slurm import SLURM_PYTHONPATH_BOOTSTRAP_BASH

logger = logging.getLogger(__name__)


def generate_slurm_directives(
    job_name: str, slurm_args: Dict[str, Any], output_log: Path, error_log: Path
) -> str:
    """Generate SBATCH directive lines for SLURM script.

    Delegates to ``phenotypic.sdk_.slurm._sbatch.format_sbatch_directives``.

    Args:
        job_name: Job name.
        slurm_args: SLURM parameters dict.
        output_log: Path for stdout log.
        error_log: Path for stderr log.

    Returns:
        String with all ``#SBATCH`` directives.
    """
    return _format_sbatch_directives(
        job_name=job_name,
        slurm_args=slurm_args,
        output_log=output_log,
        error_log=error_log,
    )


def generate_image_processing_script(
    image_path: Path,
    dataset: Dataset,
    config: ExecutionConfig,
    output_dir: Path,
    event_log: Path,
    script_dir: Path,
) -> Path:
    """
    Generate standalone bash script for processing a single image.

    Args:
        image_path: Path to image file
        dataset: Dataset containing this image
        config: Execution configuration
        output_dir: Base output directory
        event_log: Path to event log file
        script_dir: Directory to save script in

    Returns:
        Path to generated script file
    """
    # Create script directory
    script_dir.mkdir(parents=True, exist_ok=True)

    # Generate job name
    image_stem = image_path.stem
    job_name = f"pht-{dataset.name}-{image_stem}"

    # Generate log paths
    log_dir = logs_dir(output_dir) / "slurm" / dataset.name
    log_dir.mkdir(parents=True, exist_ok=True)
    output_log = log_dir / f"{image_stem}_%j.out"
    error_log = log_dir / f"{image_stem}_%j.err"

    # Generate SBATCH directives
    directives = generate_slurm_directives(
        job_name=job_name,
        slurm_args=config.slurm_args,
        output_log=output_log,
        error_log=error_log,
    )

    # Get Python command (uses uv run python if available)
    python_cmd, _ = get_python_command()

    # Build command arguments
    cmd_parts = [
        *python_cmd,
        "-m",
        "phenotypic._cli._cli_process_single",
        "--pipeline",
        shlex.quote(str(config.pipeline_json.absolute())),
        "--image",
        shlex.quote(str(image_path.absolute())),
        "--output-dir",
        shlex.quote(str(output_dir.absolute())),
        "--dataset-name",
        shlex.quote(dataset.name),
        "--image-type",
        config.image_type,
    ]

    # Omit when unset so the worker falls back to the pipeline's preset.
    if config.image_type == "GridImage":
        if config.nrows is not None:
            cmd_parts.extend(["--nrows", str(config.nrows)])
        if config.ncols is not None:
            cmd_parts.extend(["--ncols", str(config.ncols)])

    # Add bit depth if specified
    if config.bit_depth is not None:
        cmd_parts.extend(["--bit-depth", str(config.bit_depth)])

    # Add extension if non-default
    if config.ext != ".tiff":
        cmd_parts.extend(["--ext", config.ext])

    # Add overlay alpha if non-default
    if config.overlay_alpha != 0.3:
        cmd_parts.extend(["--overlay-alpha", str(config.overlay_alpha)])

    # Add dataset column flag
    if config.include_dataset_column:
        cmd_parts.append("--include-dataset-column")

    # Tri-state: emit only an explicit choice so an unset flag still lets the
    # worker auto-detect SLURM on its own node (spec §3.7).
    if config.durable_writes is not None:
        cmd_parts.append(
            "--durable-writes"
            if config.durable_writes
            else "--no-durable-writes"
        )

    # Add event log
    cmd_parts.extend(["--event-log", shlex.quote(str(event_log.absolute()))])

    # Join command
    cmd = " \\\n    ".join(cmd_parts)

    # Generate complete script
    script_content = f"""#!/bin/bash
{directives}

# Auto-generated by PhenoTypic CLI v2.0
# Image: {dataset.name}/{image_path.name}
# Pipeline: {config.pipeline_json}

set -e  # Exit on error
set -u  # Exit on undefined variable

{SLURM_PYTHONPATH_BOOTSTRAP_BASH}

{SLURM_THREAD_PIN_BASH}

# Record start time
echo "Job started: $(date)"
echo "Node: $(hostname)"
echo "Job ID: ${{SLURM_JOB_ID:-local}}"

# Run processing
{cmd}

echo "Job completed: $(date)"
exit 0
"""

    # Write script
    script_path = script_dir / f"{dataset.name}_{image_stem}.sh"
    script_path.write_text(script_content, encoding="utf-8")
    script_path.chmod(0o755)  # Make executable

    return script_path


def generate_all_image_scripts(
    datasets: List[Dataset], config: ExecutionConfig, output_dir: Path
) -> Dict[str, List[Path]]:
    """
    Generate bash scripts for all images across all datasets.

    Args:
        datasets: List of datasets to process
        config: Execution configuration
        output_dir: Base output directory

    Returns:
        Dictionary mapping dataset names to lists of script paths
    """
    script_dir = slurm_scripts_dir(output_dir)
    event_log = event_log_path(output_dir)

    all_scripts = {}

    for dataset in datasets:
        dataset_scripts = []

        for image_path in dataset.images:
            script_path = generate_image_processing_script(
                image_path=image_path,
                dataset=dataset,
                config=config,
                output_dir=output_dir,
                event_log=event_log,
                script_dir=script_dir / dataset.name,
            )
            dataset_scripts.append(script_path)

        all_scripts[dataset.name] = dataset_scripts

    return all_scripts
