package:
  name: PhenoTypic
  version: "0.4.0a"

source:
  path: ..

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - opencv
    - scikit-_root_image
    - scipy
    - pandas
    - matplotlib
    - seaborn

about:
  home: https://github.com/Wheeldon-Lab/PhenoTypic
  license: GPL-3.0
  summary: "An _root_image processing framework for rapid protocol development of phenotype _root_image analysis"

extra:
  development_status: "Development Status :: 4 - Beta"
