package:
  name: phenoscope
  version: "0.4.0a"

source:
  path: ..

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - opencv
    - scikit-image
    - scipy
    - pandas
    - matplotlib
    - seaborn

about:
  home: https://github.com/Xander-git/PhenoScope
  license: GPL-3.0
  summary: "An image processing framework for rapid protocol development of phenotype image analysis"

extra:
  development_status: "Development Status :: 4 - Beta"
