"""Overlay image viewer plugin for the Analysis tab."""

from __future__ import annotations

from phenotypic.tools_.register import register_analysis

from ._base_plugin import BaseAnalysisPlugin


@register_analysis
class ImageViewerPlugin(BaseAnalysisPlugin):
    """Overlay PNG viewer with per-image measurement data."""

    call_name = "images"
    display_name = "Image Viewer"
    sort_order = 30
    needs_measurements = False
    needs_overlay_manifest = True

    def css(self) -> str:
        """Return CSS scoped with the plugin's call_name prefix."""
        return (
            "/* Scoped: analysis-images plugin */\n"
            ".image-viewer-controls {\n"
            "  display: flex;\n"
            "  flex-wrap: wrap;\n"
            "  gap: var(--sp-3);\n"
            "  margin-bottom: var(--sp-4);\n"
            "  align-items: flex-end;\n"
            "}\n"
            ".image-viewer-controls select {\n"
            "  background: var(--color-white);\n"
            "  border: 1.5px solid var(--color-border);\n"
            "  border-radius: var(--radius);\n"
            "  padding: 0.4rem 0.6rem;\n"
            "  font-family: var(--font-mono);\n"
            "  font-size: var(--text-xs);\n"
            "  color: var(--color-body);\n"
            "  min-width: 200px;\n"
            "}\n"
            ".image-viewer-layout {\n"
            "  display: grid;\n"
            "  grid-template-columns: 1fr 1fr;\n"
            "  gap: var(--sp-4);\n"
            "}\n"
            "@media (max-width: 900px) {\n"
            "  .image-viewer-layout { grid-template-columns: 1fr; }\n"
            "}\n"
            ".image-viewer-img {\n"
            "  width: 100%;\n"
            "  border: 1px solid var(--color-border);\n"
            "  border-radius: var(--radius);\n"
            "}\n"
            ".image-viewer-img img {\n"
            "  width: 100%;\n"
            "  height: auto;\n"
            "  display: block;\n"
            "  border-radius: var(--radius);\n"
            "}\n"
            ".image-viewer-data {\n"
            "  max-height: 500px;\n"
            "  overflow-y: auto;\n"
            "}\n"
        )

    def html(self) -> str:
        """Return HTML for the sub-tab body."""
        return (
            '<div id="analysis-images-container">'
            '<div class="analysis-empty">'
            "No data available yet."
            "</div>"
            "</div>"
        )

    def js(self) -> str:
        """Return JS including an ``initAnalysis_images()`` function."""
        return (
            "function initAnalysis_images() {\n"
            "  renderImageViewer();\n"
            "}\n"
            "\n"
            "function renderImageViewer() {\n"
            "  var container = document.getElementById("
            "'analysis-images-container');\n"
            "  var d = analysisData.overlay;\n"
            "  if (!d || !d.datasets"
            " || Object.keys(d.datasets).length === 0) {\n"
            "    container.innerHTML = '<div class=\"analysis-empty\">"
            "No overlay images available yet.</div>';\n"
            "    return;\n"
            "  }\n"
            "  var dsNames = Object.keys(d.datasets);\n"
            "  var html = '<div class=\"image-viewer-controls\">';\n"
            "  html += '<div class=\"scatter-control-group\">"
            "<label>Dataset</label>"
            "<select id=\"iv-dataset\" onchange=\"updateImageList()\">';\n"
            "  dsNames.forEach(function(ds) {"
            " html += '<option value=\"' + esc(ds) + '\">' + esc(ds)"
            " + '</option>'; });\n"
            "  html += '</select></div>';\n"
            "  html += '<div class=\"scatter-control-group\">"
            "<label>Image</label>"
            "<select id=\"iv-image\" onchange=\"loadOverlayImage()\">"
            "</select></div>';\n"
            "  html += '</div>';\n"
            "  html += '<div class=\"image-viewer-layout\">';\n"
            "  html += '<div class=\"image-viewer-img\" id=\"iv-img-wrap\">"
            "<div class=\"analysis-empty\">Select an image above.</div>"
            "</div>';\n"
            "  html += '<div class=\"image-viewer-data\" id=\"iv-data-wrap\">"
            "<div class=\"analysis-empty\">"
            "Select an image to view measurements.</div>"
            "</div>';\n"
            "  html += '</div>';\n"
            "  container.innerHTML = html;\n"
            "  updateImageList();\n"
            "}\n"
            "\n"
            "function updateImageList() {\n"
            "  var d = analysisData.overlay;\n"
            "  if (!d) return;\n"
            "  var ds = document.getElementById('iv-dataset').value;\n"
            "  var images = d.datasets[ds] || [];\n"
            "  var sel = document.getElementById('iv-image');\n"
            "  sel.innerHTML = images.map(function(img) {"
            " return '<option value=\"' + esc(img) + '\">' + esc(img)"
            " + '</option>'; }).join('');\n"
            "  if (images.length > 0) loadOverlayImage();\n"
            "}\n"
            "\n"
            "function loadOverlayImage() {\n"
            "  var ds = document.getElementById('iv-dataset').value;\n"
            "  var img = document.getElementById('iv-image').value;\n"
            "  if (!ds || !img) return;\n"
            "  var imgWrap = document.getElementById('iv-img-wrap');\n"
            "  var overlayPath = 'results/' + encodeURIComponent(ds)"
            " + '/overlays/' + encodeURIComponent(img);\n"
            "  imgWrap.innerHTML = '<img src=\"' + overlayPath"
            " + '\" alt=\"' + esc(img)"
            " + '\" onerror=\"this.parentElement.innerHTML="
            "\\'<div class=analysis-empty>Image not found.</div>\\'\">';\n"
            "  var dataWrap = document.getElementById('iv-data-wrap');\n"
            "  var csvName = img.replace(/\\.png$/i, '.csv');\n"
            "  var csvPath = 'results/' + encodeURIComponent(ds)"
            " + '/measurements/' + encodeURIComponent(csvName);\n"
            "  fetch(csvPath + '?' + Date.now()).then(function(resp) {\n"
            "    if (!resp.ok) {"
            " dataWrap.innerHTML = '<div class=\"analysis-empty\">"
            "No measurement data for this image.</div>'; return; }\n"
            "    return resp.text();\n"
            "  }).then(function(text) {\n"
            "    if (!text) return;\n"
            "    var lines = text.trim().split('\\n');\n"
            "    if (lines.length < 2) {"
            " dataWrap.innerHTML = '<div class=\"analysis-empty\">"
            "Empty measurement file.</div>'; return; }\n"
            "    var headers = lines[0].split(',');\n"
            "    var thtml = '<table class=\"analysis-table\">"
            "<thead><tr>';\n"
            "    headers.forEach(function(h) {"
            " thtml += '<th>' + esc(h.trim()) + '</th>'; });\n"
            "    thtml += '</tr></thead><tbody>';\n"
            "    for (var r = 1; r < lines.length; r++) {\n"
            "      var cells = lines[r].split(',');\n"
            "      thtml += '<tr>';\n"
            "      cells.forEach(function(c) {"
            " thtml += '<td>' + esc(c.trim()) + '</td>'; });\n"
            "      thtml += '</tr>';\n"
            "    }\n"
            "    thtml += '</tbody></table>';\n"
            "    dataWrap.innerHTML = thtml;\n"
            "  }).catch(function() {\n"
            "    dataWrap.innerHTML = '<div class=\"analysis-empty\">"
            "Could not load measurement data.</div>';\n"
            "  });\n"
            "}\n"
        )
