"""Raw data table plugin for the Analysis tab."""

from __future__ import annotations

from phenotypic.tools_.register import register_analysis

from ._base_plugin import BaseAnalysisPlugin


@register_analysis
class RawTablePlugin(BaseAnalysisPlugin):
    """Paginated raw results table with sorting and column visibility toggles."""

    call_name = "table"
    display_name = "Raw Table"
    sort_order = 5
    needs_measurements = True
    needs_overlay_manifest = False

    def css(self) -> str:
        """Return CSS scoped with the plugin's call_name prefix."""
        return (
            "/* Scoped: analysis-table plugin */\n"
            ".analysis-table {\n"
            "  width: 100%;\n"
            "  border-collapse: collapse;\n"
            "  font-size: var(--text-sm);\n"
            "}\n"
            ".analysis-table th {\n"
            "  text-align: left;\n"
            "  padding: 10px 12px;\n"
            "  font-family: var(--font-mono);\n"
            "  font-size: 0.6875rem;\n"
            "  text-transform: uppercase;\n"
            "  letter-spacing: 0.08em;\n"
            "  color: var(--color-muted);\n"
            "  border-bottom: 2px solid var(--color-navy);\n"
            "  white-space: nowrap;\n"
            "  cursor: pointer;\n"
            "  user-select: none;\n"
            "  position: relative;\n"
            "}\n"
            ".analysis-table th:hover { color: var(--color-navy); }\n"
            ".analysis-table th .sort-icon { margin-left: 4px; opacity: 0.4; }\n"
            ".analysis-table th.sort-active .sort-icon {"
            " opacity: 1; color: var(--color-navy); }\n"
            ".analysis-table td {\n"
            "  padding: 8px 12px;\n"
            "  border-bottom: 1px solid var(--color-rule);\n"
            "  font-family: var(--font-mono);\n"
            "  font-size: var(--text-xs);\n"
            "  color: var(--color-body);\n"
            "  max-width: 200px;\n"
            "  overflow: hidden;\n"
            "  text-overflow: ellipsis;\n"
            "  white-space: nowrap;\n"
            "}\n"
            ".analysis-table tbody tr:hover td {"
            " background: rgba(27,117,188,0.03); }\n"
            ".analysis-table-wrapper {\n"
            "  overflow-x: auto;\n"
            "  margin-bottom: var(--sp-4);\n"
            "}\n"
            ".analysis-pagination {\n"
            "  display: flex;\n"
            "  align-items: center;\n"
            "  justify-content: center;\n"
            "  gap: var(--sp-3);\n"
            "  padding: var(--sp-3) 0;\n"
            "  font-family: var(--font-mono);\n"
            "  font-size: var(--text-xs);\n"
            "  color: var(--color-muted);\n"
            "}\n"
            ".analysis-pagination button {\n"
            "  background: none;\n"
            "  border: 1.5px solid var(--color-border);\n"
            "  border-radius: var(--radius);\n"
            "  padding: 0.3rem 0.75rem;\n"
            "  font-family: var(--font-body);\n"
            "  font-size: 11px;\n"
            "  font-weight: 500;\n"
            "  color: var(--color-navy);\n"
            "  cursor: pointer;\n"
            "  transition: all var(--transition);\n"
            "}\n"
            ".analysis-pagination button:hover {"
            " border-color: var(--color-blue);"
            " color: var(--color-blue);"
            " background: rgba(27,117,188,0.04); }\n"
            ".analysis-pagination button:disabled {"
            " opacity: 0.4; cursor: default;"
            " border-color: var(--color-border);"
            " color: var(--color-muted); background: none; }\n"
            ".column-toggle-wrap {\n"
            "  margin-bottom: var(--sp-4);\n"
            "}\n"
            ".column-toggle-btn {\n"
            "  background: none;\n"
            "  border: 1.5px solid var(--color-border);\n"
            "  border-radius: var(--radius);\n"
            "  padding: 0.3rem 0.75rem;\n"
            "  font-family: var(--font-body);\n"
            "  font-size: 11px;\n"
            "  font-weight: 500;\n"
            "  color: var(--color-navy);\n"
            "  cursor: pointer;\n"
            "  transition: all var(--transition);\n"
            "}\n"
            ".column-toggle-btn:hover {"
            " border-color: var(--color-blue); }\n"
            ".column-toggle-panel {\n"
            "  display: none;\n"
            "  margin-top: var(--sp-2);\n"
            "  padding: var(--sp-3);\n"
            "  background: var(--color-bg);\n"
            "  border: 1px solid var(--color-border);\n"
            "  border-radius: var(--radius);\n"
            "  max-height: 300px;\n"
            "  overflow-y: auto;\n"
            "}\n"
            ".column-toggle-panel.open { display: block; }\n"
            ".column-group-label {\n"
            "  font-family: var(--font-mono);\n"
            "  font-size: var(--text-xs);\n"
            "  font-weight: 500;\n"
            "  color: var(--color-heading);\n"
            "  text-transform: uppercase;\n"
            "  letter-spacing: 0.08em;\n"
            "  margin: var(--sp-2) 0 var(--sp-1);\n"
            "}\n"
            ".column-group-label:first-child { margin-top: 0; }\n"
            ".column-toggle-panel label {\n"
            "  display: inline-flex;\n"
            "  align-items: center;\n"
            "  gap: 4px;\n"
            "  margin-right: var(--sp-3);\n"
            "  font-family: var(--font-mono);\n"
            "  font-size: var(--text-xs);\n"
            "  color: var(--color-body);\n"
            "  cursor: pointer;\n"
            "}\n"
        )

    def html(self) -> str:
        """Return HTML for the sub-tab body."""
        return (
            '<div id="analysis-table-container">'
            '<div class="analysis-empty">'
            "No data available yet. Data will appear after processing"
            " completes."
            "</div>"
            "</div>"
        )

    def js(self) -> str:
        """Return JS including an ``initAnalysis_table()`` function."""
        return (
            "var tableState = { page: 0, pageSize: 50, sortCol: null,"
            " sortAsc: true, visibleCols: null, data: null };\n"
            "\n"
            "function initAnalysis_table() {\n"
            "  renderRawTable();\n"
            "}\n"
            "\n"
            "function renderRawTable() {\n"
            "  var container = document.getElementById("
            "'analysis-table-container');\n"
            "  var d = analysisData.table;\n"
            "  if (!d || !d.columns || d.columns.length === 0) {\n"
            "    container.innerHTML = '<div class=\"analysis-empty\">"
            "No data available yet.</div>';\n"
            "    return;\n"
            "  }\n"
            "  tableState.data = d;\n"
            "  if (!tableState.visibleCols) tableState.visibleCols ="
            " new Set(d.columns.slice(0, 20));\n"
            "  tableState.page = 0;\n"
            "  renderTableContent(container);\n"
            "}\n"
            "\n"
            "function renderTableContent(container) {\n"
            "  var d = tableState.data;\n"
            "  if (!d) return;\n"
            "  var cols = d.columns.filter(function(c) {"
            " return tableState.visibleCols.has(c); });\n"
            "  var nRows = d.data[d.columns[0]].length;\n"
            "  var indices = Array.from({length: nRows},"
            " function(_, i) { return i; });\n"
            "  if (tableState.sortCol && d.data[tableState.sortCol]) {\n"
            "    var vals = d.data[tableState.sortCol];\n"
            "    indices.sort(function(a, b) {\n"
            "      var va = vals[a], vb = vals[b];\n"
            "      if (va === null || va === undefined) return 1;\n"
            "      if (vb === null || vb === undefined) return -1;\n"
            "      if (typeof va === 'string') return tableState.sortAsc ?"
            " va.localeCompare(vb) : vb.localeCompare(va);\n"
            "      return tableState.sortAsc ? va - vb : vb - va;\n"
            "    });\n"
            "  }\n"
            "  var start = tableState.page * tableState.pageSize;\n"
            "  var end = Math.min(start + tableState.pageSize, nRows);\n"
            "  var pageIndices = indices.slice(start, end);\n"
            "  var totalPages = Math.ceil(nRows / tableState.pageSize);\n"
            "  var groups = {};\n"
            "  d.columns.forEach(function(c) {\n"
            "    var g = c.indexOf('_') > 0 ?"
            " c.substring(0, c.indexOf('_')) : 'Other';\n"
            "    if (!groups[g]) groups[g] = [];\n"
            "    groups[g].push(c);\n"
            "  });\n"
            "  var html = '';\n"
            "  if (d.sampled) {\n"
            "    html += '<div class=\"analysis-sample-label\">Showing '"
            " + nRows.toLocaleString() + ' of '"
            " + d.total_rows.toLocaleString()"
            " + ' rows (sampled)</div>';\n"
            "  }\n"
            "  html += '<div class=\"column-toggle-wrap\">';\n"
            "  html += '<button class=\"column-toggle-btn\""
            " onclick=\"toggleColumnPanel()\">Toggle Columns ('"
            " + cols.length + '/' + d.columns.length"
            " + ')</button>';\n"
            "  html += '<div class=\"column-toggle-panel\""
            " id=\"col-toggle-panel\">';\n"
            "  for (var group in groups) {\n"
            "    html += '<div class=\"column-group-label\">'"
            " + esc(group) + '</div>';\n"
            "    groups[group].forEach(function(c) {\n"
            "      var checked = tableState.visibleCols.has(c)"
            " ? ' checked' : '';\n"
            "      html += '<label><input type=\"checkbox\""
            " onchange=\"toggleColumn(\\'' + esc(c)"
            " + '\\')\"' + checked + '> '"
            " + esc(c) + '</label>';\n"
            "    });\n"
            "  }\n"
            "  html += '</div></div>';\n"
            "  html += '<div class=\"analysis-table-wrapper\">"
            "<table class=\"analysis-table\"><thead><tr>';\n"
            "  cols.forEach(function(c) {\n"
            "    var sortCls = tableState.sortCol === c"
            " ? ' sort-active' : '';\n"
            "    var arrow = tableState.sortCol === c"
            " ? (tableState.sortAsc ? '&#9650;' : '&#9660;')"
            " : '&#9650;';\n"
            "    html += '<th class=\"' + sortCls"
            " + '\" onclick=\"sortTable(\\'' + esc(c)"
            " + '\\')\">' + esc(c)"
            " + '<span class=\"sort-icon\">' + arrow"
            " + '</span></th>';\n"
            "  });\n"
            "  html += '</tr></thead><tbody>';\n"
            "  pageIndices.forEach(function(idx) {\n"
            "    html += '<tr>';\n"
            "    cols.forEach(function(c) {\n"
            "      var v = d.data[c][idx];\n"
            "      var display = v === null || v === undefined ? ''"
            " : (typeof v === 'number'"
            " ? (Number.isInteger(v)"
            " ? v.toLocaleString() : v.toFixed(4))"
            " : String(v));\n"
            "      html += '<td>' + esc(display) + '</td>';\n"
            "    });\n"
            "    html += '</tr>';\n"
            "  });\n"
            "  html += '</tbody></table></div>';\n"
            "  html += '<div class=\"analysis-pagination\">';\n"
            "  html += '<button onclick=\"tablePrevPage()\" '"
            " + (tableState.page <= 0 ? 'disabled' : '')"
            " + '>&laquo; Prev</button>';\n"
            "  html += '<span>Page '"
            " + (tableState.page + 1) + ' of '"
            " + totalPages + '</span>';\n"
            "  html += '<button onclick=\"tableNextPage()\" '"
            " + (tableState.page >= totalPages - 1 ? 'disabled' : '')"
            " + '>Next &raquo;</button>';\n"
            "  html += '</div>';\n"
            "  container.innerHTML = html;\n"
            "}\n"
            "\n"
            "function sortTable(col) {\n"
            "  if (tableState.sortCol === col)"
            " tableState.sortAsc = !tableState.sortAsc;\n"
            "  else { tableState.sortCol = col;"
            " tableState.sortAsc = true; }\n"
            "  tableState.page = 0;\n"
            "  renderTableContent("
            "document.getElementById('analysis-table-container'));\n"
            "}\n"
            "function tablePrevPage() {"
            " if (tableState.page > 0) {"
            " tableState.page--;"
            " renderTableContent("
            "document.getElementById('analysis-table-container'));"
            " } }\n"
            "function tableNextPage() {"
            " var d = tableState.data;"
            " if (d) {"
            " var n = d.data[d.columns[0]].length;"
            " if ((tableState.page+1)*tableState.pageSize < n) {"
            " tableState.page++;"
            " renderTableContent("
            "document.getElementById('analysis-table-container'));"
            " } } }\n"
            "function toggleColumnPanel() {"
            " document.getElementById('col-toggle-panel')"
            ".classList.toggle('open'); }\n"
            "function toggleColumn(col) {\n"
            "  if (tableState.visibleCols.has(col))"
            " tableState.visibleCols.delete(col);\n"
            "  else tableState.visibleCols.add(col);\n"
            "  renderTableContent("
            "document.getElementById('analysis-table-container'));\n"
            "}\n"
        )
