"""Summary statistics plugin for the Analysis tab."""

from __future__ import annotations

from phenotypic.tools_.register import register_analysis

from ._base_plugin import BaseAnalysisPlugin


@register_analysis
class SummaryStatsPlugin(BaseAnalysisPlugin):
    """Pre-computed per-dataset descriptive statistics with CV flagging."""

    call_name = "stats"
    display_name = "Statistics"
    sort_order = 20
    needs_measurements = True
    needs_overlay_manifest = False

    def css(self) -> str:
        """Return CSS scoped with the plugin's call_name prefix."""
        return (
            "/* Scoped: analysis-stats plugin */\n"
            ".stats-controls {\n"
            "  margin-bottom: var(--sp-4);\n"
            "}\n"
            ".stats-controls select {\n"
            "  background: var(--color-white);\n"
            "  border: 1.5px solid var(--color-border);\n"
            "  border-radius: var(--radius);\n"
            "  padding: 0.4rem 0.6rem;\n"
            "  font-family: var(--font-mono);\n"
            "  font-size: var(--text-xs);\n"
            "  color: var(--color-body);\n"
            "  min-width: 200px;\n"
            "}\n"
            ".stats-table-wrapper { overflow-x: auto; }\n"
            ".stats-table {\n"
            "  width: 100%;\n"
            "  border-collapse: collapse;\n"
            "  font-size: var(--text-sm);\n"
            "}\n"
            ".stats-table th {\n"
            "  text-align: left;\n"
            "  padding: 10px 12px;\n"
            "  font-family: var(--font-mono);\n"
            "  font-size: 0.6875rem;\n"
            "  text-transform: uppercase;\n"
            "  letter-spacing: 0.08em;\n"
            "  color: var(--color-muted);\n"
            "  border-bottom: 2px solid var(--color-navy);\n"
            "  white-space: nowrap;\n"
            "}\n"
            ".stats-table td {\n"
            "  padding: 8px 12px;\n"
            "  border-bottom: 1px solid var(--color-rule);\n"
            "  font-family: var(--font-mono);\n"
            "  font-size: var(--text-xs);\n"
            "  color: var(--color-body);\n"
            "  white-space: nowrap;\n"
            "}\n"
            ".stats-table tbody tr:hover td {"
            " background: rgba(27,117,188,0.03); }\n"
            ".stats-table td.cv-high {"
            " color: #D55E00; font-weight: 500; }\n"
        )

    def html(self) -> str:
        """Return HTML for the sub-tab body."""
        return (
            '<div id="analysis-stats-container">'
            '<div class="analysis-empty">'
            "No data available yet."
            "</div>"
            "</div>"
        )

    def js(self) -> str:
        """Return JS including an ``initAnalysis_stats()`` function."""
        return (
            "function initAnalysis_stats() {\n"
            "  renderSummaryStats();\n"
            "}\n"
            "\n"
            "function renderSummaryStats() {\n"
            "  var container = document.getElementById("
            "'analysis-stats-container');\n"
            "  var d = analysisData.stats;\n"
            "  if (!d || !d.datasets"
            " || Object.keys(d.datasets).length === 0) {\n"
            "    container.innerHTML = '<div class=\"analysis-empty\">"
            "No data available yet.</div>';\n"
            "    return;\n"
            "  }\n"
            "  var dsNames = Object.keys(d.datasets);\n"
            "  var html = '<div class=\"stats-controls\">"
            "<select id=\"stats-dataset\""
            " onchange=\"updateStatsTable()\">';\n"
            "  dsNames.forEach(function(ds) {"
            " html += '<option value=\"' + esc(ds) + '\">' + esc(ds)"
            " + '</option>'; });\n"
            "  html += '</select></div>';\n"
            "  html += '<div id=\"stats-table-wrap\"></div>';\n"
            "  container.innerHTML = html;\n"
            "  updateStatsTable();\n"
            "}\n"
            "\n"
            "function updateStatsTable() {\n"
            "  var d = analysisData.stats;\n"
            "  if (!d) return;\n"
            "  var ds = document.getElementById('stats-dataset').value;\n"
            "  var dsData = d.datasets[ds];\n"
            "  if (!dsData || !dsData.columns) {\n"
            "    document.getElementById('stats-table-wrap').innerHTML ="
            " '<div class=\"analysis-empty\">"
            "No data for this dataset.</div>';\n"
            "    return;\n"
            "  }\n"
            "  var statKeys ="
            " ['count','mean','std','min','median','max','cv'];\n"
            "  var html = '<div class=\"stats-table-wrapper\">"
            "<table class=\"stats-table\"><thead><tr><th>Column</th>';\n"
            "  statKeys.forEach(function(k) {"
            " html += '<th>' + k.toUpperCase() + '</th>'; });\n"
            "  html += '</tr></thead><tbody>';\n"
            "  var sortedCols = Object.keys(dsData.columns)"
            ".sort(function(a, b) {\n"
            "    var ga = a.indexOf('_') > 0"
            " ? a.substring(0, a.indexOf('_')) : 'ZZZ';\n"
            "    var gb = b.indexOf('_') > 0"
            " ? b.substring(0, b.indexOf('_')) : 'ZZZ';\n"
            "    if (ga !== gb) return ga.localeCompare(gb);\n"
            "    return a.localeCompare(b);\n"
            "  });\n"
            "  sortedCols.forEach(function(col) {\n"
            "    var s = dsData.columns[col];\n"
            "    html += '<tr><td style=\"font-weight:500;"
            "color:var(--color-heading)\">' + esc(col) + '</td>';\n"
            "    statKeys.forEach(function(k) {\n"
            "      var v = s[k];\n"
            "      var display = v === null || v === undefined ? '-'"
            " : (typeof v === 'number'"
            " ? (Number.isInteger(v)"
            " ? v.toLocaleString() : v.toFixed(4))"
            " : String(v));\n"
            "      var cls = (k === 'cv' && typeof v === 'number'"
            " && v > 25) ? ' class=\"cv-high\"' : '';\n"
            "      html += '<td' + cls + '>' + esc(display)"
            " + '</td>';\n"
            "    });\n"
            "    html += '</tr>';\n"
            "  });\n"
            "  html += '</tbody></table></div>';\n"
            "  document.getElementById('stats-table-wrap')"
            ".innerHTML = html;\n"
            "}\n"
        )
