"""SLURM array job script generation for the sweep CLI.

Generates bash scripts that process one image per array task, running all
pipelines sequentially within each task.
"""

from __future__ import annotations

import shlex
from pathlib import Path
from typing import Any, Dict, List, Optional

from phenotypic._cli._cli_slurm_scripts import generate_slurm_directives
from phenotypic._cli._cli_utils import get_python_command


def generate_sweep_array_script(
    image_paths: List[Path],
    manifest_path: Path,
    output_dir: Path,
    image_type: str,
    read_kwargs: Dict[str, Any],
    slurm_args: Dict[str, Any],
    save_layers: Optional[Dict[str, bool]] = None,
    overlay_mode: str = "image",
    overlay_alpha: float = 0.3,
) -> Path:
    """Generate a SLURM array job script for sweep processing.

    Each array task processes **one image** through all pipelines
    sequentially, via the ``phenotypic.sweep._sweep_process_image`` sub-CLI.

    Args:
        image_paths: All images to process.
        manifest_path: Path to the sweep manifest JSON.
        output_dir: Base output directory.
        image_type: ``"Image"`` or ``"GridImage"``.
        read_kwargs: Image read kwargs (nrows, ncols, etc.).
        slurm_args: SLURM parameters dict.
        save_layers: Which layers to save.
        overlay_mode: Overlay saving mode.
        overlay_alpha: Overlay transparency.

    Returns:
        Path to the generated script.
    """
    save_layers = save_layers or {}

    # Create script directory
    script_dir = output_dir / "slurm_scripts"
    script_dir.mkdir(parents=True, exist_ok=True)

    # Log paths
    log_dir = output_dir / "logs" / "slurm"
    log_dir.mkdir(parents=True, exist_ok=True)
    log_path = log_dir / "sweep_%A_%a.log"

    # Generate SBATCH directives
    directives = generate_slurm_directives(
        job_name="pheno-sweep",
        slurm_args=slurm_args,
        output_log=log_path,
        error_log=log_path,
    )

    # Array directive
    num_tasks = len(image_paths)
    array_directive = f"#SBATCH --array=0-{num_tasks - 1}"

    # Build image list for bash array
    image_list_lines = []
    for img in image_paths:
        image_list_lines.append(f"    {shlex.quote(str(img.absolute()))}")
    image_list_content = "\n".join(image_list_lines)

    # Build command
    event_log = output_dir / "processing_events.log"
    python_cmd, _ = get_python_command()

    cmd_parts = [
        *python_cmd,
        "-m",
        "phenotypic.sweep._sweep_process_image",
        "--manifest",
        shlex.quote(str(manifest_path.absolute())),
        "--image",
        '"${CURRENT_IMAGE}"',
        "--output-dir",
        shlex.quote(str(output_dir.absolute())),
        "--image-type",
        image_type,
    ]

    # Grid params
    nrows = read_kwargs.get("nrows")
    ncols = read_kwargs.get("ncols")
    if image_type == "GridImage":
        cmd_parts.extend(["--nrows", str(nrows or 8)])
        cmd_parts.extend(["--ncols", str(ncols or 12)])

    bit_depth = read_kwargs.get("bit_depth")
    if bit_depth is not None:
        cmd_parts.extend(["--bit-depth", str(bit_depth)])

    detect_mode = read_kwargs.get("detect_mode", "gray")
    if detect_mode != "gray":
        cmd_parts.extend(["--detect-mode", detect_mode])

    # Save layer flags
    if save_layers.get("rgb"):
        cmd_parts.append("--save-rgb")
    if save_layers.get("gray"):
        cmd_parts.append("--save-gray")
    if save_layers.get("detect_mat"):
        cmd_parts.append("--save-detect-mat")
    if save_layers.get("objmask"):
        cmd_parts.append("--save-objmask")
    if save_layers.get("objmap"):
        cmd_parts.append("--save-objmap")
    if save_layers.get("objmap_overlay"):
        cmd_parts.append("--save-objmap-overlay")
    if save_layers.get("detect_mat_overlay"):
        cmd_parts.append("--save-detect-mat-overlay")
    if save_layers.get("objmask_overlay"):
        cmd_parts.append("--save-objmask-overlay")

    cmd_parts.extend(["--overlay-mode", overlay_mode])
    cmd_parts.extend(["--overlay-alpha", str(overlay_alpha)])
    cmd_parts.extend(["--event-log", shlex.quote(str(event_log.absolute()))])

    cmd = " \\\n    ".join(cmd_parts)

    script_content = f"""#!/bin/bash
{directives}
{array_directive}

# Auto-generated by PhenoTypic Sweep CLI
# Manifest: {manifest_path}
# Images: {num_tasks}

set -u

echo "======================================"
echo "Job ID: ${{SLURM_JOB_ID:-unknown}}"
echo "Array Task ID: ${{SLURM_ARRAY_TASK_ID:-unknown}}"
echo "Node: ${{SLURMD_NODENAME:-$(hostname)}}"
echo "Start Time: $(date)"
echo "======================================"

IMAGE_LIST=(
{image_list_content}
)

if [ "${{SLURM_ARRAY_TASK_ID:-}}" = "" ]; then
    echo "ERROR: SLURM_ARRAY_TASK_ID not set"
    exit 1
fi

if [ "$SLURM_ARRAY_TASK_ID" -ge "${{#IMAGE_LIST[@]}}" ]; then
    echo "ERROR: Array task ID exceeds image list size"
    exit 1
fi

CURRENT_IMAGE="${{IMAGE_LIST[$SLURM_ARRAY_TASK_ID]}}"

echo "Processing image $((SLURM_ARRAY_TASK_ID + 1))/${{#IMAGE_LIST[@]}}: $CURRENT_IMAGE"
echo ""

{cmd}

EXIT_CODE=$?

echo ""
echo "======================================"
echo "Exit Code: $EXIT_CODE"
echo "End Time: $(date)"
echo "======================================"

exit $EXIT_CODE
"""

    script_path = script_dir / "sweep_array_job.sh"
    script_path.write_text(script_content)
    script_path.chmod(0o755)

    return script_path
